spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    locations: classpath:db
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: training_app
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
  datasource:
    url: jdbc:postgresql://localhost:5432/training_app
    username: postgres
    password: postgres
  application:
    name: main-api
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true

server:
  port: 8081
logging:
  level:
    org.example.logging.*: DEBUG
jwt:
  secret: 6013fba8-50ec-4830-a6b6-1c2b7ef27b3a
  expiration: 3600000
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
feign:
  circuitbreaker:
    enabled: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/training_app_dev
    username: postgres
    password: postgres

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/training_app_prod
    username: postgres
    password: postgres