spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    locations: classpath:db
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: training_app
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
  datasource:
    url: jdbc:postgresql://localhost:5432/training_app
    username: postgres
    password: postgres
server:
  port: 8081
logging:
  level:
    org.example.logging.*: DEBUG