spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    locations: classpath:db
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: training_app
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
  datasource:
    url: jdbc:postgresql://localhost:5432/training_app
    username: postgres
    password: postgres
server:
  port: 8081
logging:
  level:
    org.example.logging.*: DEBUG
jwt:
  secret: 6013fba8-50ec-4830-a6b6-1c2b7ef27b3a
  expiration: 3600000
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/training_app_dev
    username: postgres
    password: postgres