spring:
  application:
    name: second-api
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    jpa:
      repositories:
        bootstrap-mode: default
    mongodb:
      uri: mongodb+srv://epam-learn:1fBajmXpG7jNEmrR@mongodb-test.pfcyb8s.mongodb.net/test_db?retryWrites=true&w=majority&appName=MongoDB-test
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  jms:
    template:
      qos-enabled: true

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
jwt:
  secret: 6013fba8-50ec-4830-a6b6-1c2b7ef27b3b
  expiration: 3600000

---
spring:
  config:
    activate:
      on-profile: test
#  activemq:
#    broker-url: tcp://localhost:5656
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:5657/eureka}
  activemq:
    broker-url: tcp://activemq:61616
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}
server:
  port: 8080
